/* eslint-disable no-console */
import * as fs from 'fs'
import * as path from 'path'
import * as jsYaml from 'js-yaml'
import fg from 'fast-glob'
import { pathToFileURL } from 'url'
import { Context, type Workflow } from '@github-actions-workflow-ts/lib'
import type { WacConfig } from './types/index.js'
import { ConsoleDiagnosticsReporter } from './diagnostics.js'

/**
 * Comment indicating the file should not be modified.
 * @type {string}
 */
export const DEFAULT_HEADER_TEXT = [
  '# ------------DO-NOT-MODIFY-THIS-FILE------------',
  '# This file was automatically generated by github-actions-workflow-ts.',
  '# Instead, modify <source-file-path>',
  '# ------------DO-NOT-MODIFY-THIS-FILE------------',
]

/**
 * Convert an absolute path to a relative path from the current working directory.
 *
 * @param {string} p - The absolute path.
 * @returns {string} - Relative path from the current working directory.
 */
export const relativePath = (p: string): string =>
  path.relative(process.cwd(), p)

/**
 * Returns the config file
 * @returns { Record<string, any> | undefined} - The config file as an object
 */
export const getConfig = (): WacConfig | undefined => {
  const configFilePath = path.join(process.cwd(), 'wac.config.json')

  if (!fs.existsSync(configFilePath)) {
    console.log(
      '[github-actions-workflow-ts] No config (wac.config.json) file found in root dir. Using default config.',
    )

    return undefined
  }

  console.log(
    '[github-actions-workflow-ts] wac.config.json config file found in root dir',
  )

  return JSON.parse(fs.readFileSync(configFilePath, 'utf-8'))
}

/**
 * Retrieves the file paths of all workflow files in the project.
 *
 * @returns {string[] | undefined} - Array of paths to *.wac.ts files or undefined if none are found.
 */
export const getWorkflowFilePaths = (): string[] | undefined => {
  const workflowFilesPaths = fg.sync(
    fg.convertPathToPattern(process.cwd()) + '/**/*.wac.ts',
    {
      onlyFiles: true,
      dot: true,
    },
  )

  if (!workflowFilesPaths || !workflowFilesPaths.length) {
    console.log(
      '[github-actions-workflow-ts] No workflow files found. Please create at least one *.wac.ts file in your project',
    )

    return
  }

  const workflowFileList = workflowFilesPaths
    .map((item) => `[github-actions-workflow-ts] --> ${relativePath(item)}`)
    .join('\n')

  console.log(
    `[github-actions-workflow-ts] Detected following .wac.ts files:\n${workflowFileList}`,
  )

  return workflowFilesPaths
}

/**
 * Dynamically imports a TypeScript workflow file using tsx.
 * Works with both ESM and CommonJS projects.
 *
 * @param {string} filePath - The path to the .wac.ts file.
 * @returns {Promise<Record<string, Workflow>>} - The exported workflows from the file.
 */
export const importWorkflowFile = async (
  filePath: string,
): Promise<Record<string, Workflow>> => {
  const absolutePath = path.resolve(filePath)
  const fileUrl = pathToFileURL(absolutePath).href

  // Dynamic import works with ESM - tsx loader handles TypeScript
  const module = await import(fileUrl)

  return module
}

/**
 * Writes the provided workflow JSON data to corresponding YAML files.
 *
 * @param {Record<string, Workflow>} workflowJSON - The workflow data in JSON format.
 * @param {string} workflowFilePath - The path to the workflow file.
 * @param {WacConfig} config - Command line arguments.
 * @returns {number} - The number of workflows written.
 */
export const writeWorkflowJSONToYamlFiles = (
  workflowJSON: Record<string, Workflow>,
  workflowFilePath: string,
  config: WacConfig,
): number => {
  let workflowCount: number = 0

  for (const workflowName in workflowJSON) {
    const workflow = workflowJSON[workflowName]

    // Skip non-Workflow exports (like default exports or other values)
    if (!workflow || !workflow.workflow || !workflow.filename) {
      continue
    }

    const workflowYaml = jsYaml.dump(workflow.workflow, {
      noRefs: !config.refs,
      ...(config.dumpOptions || {}),
    })

    const yamlWorkflowPath = path.join(
      '.github',
      'workflows',
      `${workflow.filename}.yml`,
    )

    console.log(
      `[github-actions-workflow-ts] Writing to ${relativePath(yamlWorkflowPath)}:`,
    )

    const headerText = (config.headerText || DEFAULT_HEADER_TEXT)
      .join('\n')
      .replace('<source-file-path>', workflowFilePath)

    fs.writeFileSync(yamlWorkflowPath, [headerText, workflowYaml].join('\n'))

    workflowCount++
  }

  return workflowCount
}

/**
 * Creates the .github/workflows directory if it doesn't exist.
 */
export const createWorkflowDirectory = (): void => {
  const workflowsDir = relativePath(path.join('.github', 'workflows'))

  if (!fs.existsSync(workflowsDir)) {
    console.log(
      '[github-actions-workflow-ts] .github/workflows directory not found. Creating it.',
    )
    fs.mkdirSync(workflowsDir, { recursive: true })
  }
}

/**
 * Generates workflow files based on the provided command line arguments.
 *
 * @param {Record<string, unknown>} argv - Command line arguments.
 * @returns {Promise<void>} - A promise that resolves when the generation is completed.
 */
export const generateWorkflowFiles = async (
  argv: Record<string, unknown>,
): Promise<void> => {
  const config = getConfig() || {}
  const workflowFilePaths = getWorkflowFilePaths() || []
  let workflowCount = 0

  createWorkflowDirectory()

  Context.__internalSetGlobalContext({
    diagnostics: new ConsoleDiagnosticsReporter(),
  })

  for (const filePath of workflowFilePaths) {
    const workflows = await importWorkflowFile(filePath)
    workflowCount += writeWorkflowJSONToYamlFiles(
      workflows,
      relativePath(filePath),
      {
        ...argv,
        ...config,
      } as WacConfig,
    )
  }

  console.log(
    `[github-actions-workflow-ts] Successfully generated ${workflowCount} workflow file(s)`,
  )
}
