name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: "New"
    label: "feature"
  - title: "Chore"
    label: "chore"
  - title: "Refactor"
    label: "refactor"
  - title: "CI"
    label: "ci"
  - title: "Breaking"
    label: "breaking"
  - title: "Bug Fixes"
    label: "bug"
  - title: "Documentation"
    label: "docs"
  - title: "Tests"
    label: "test"
  - title: "Other"
  - title: "Dependency Updates"
    label: "dependencies"
    collapse-after: 5

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "maintenance"
      - "docs"
      - "dependencies"
      - "security"

exclude-labels:
  - "skip-changelog"
