import type { ReactNode } from 'react'
import clsx from 'clsx'
import Link from '@docusaurus/Link'
import useDocusaurusContext from '@docusaurus/useDocusaurusContext'
import Layout from '@theme/Layout'
import Heading from '@theme/Heading'
import CodeBlock from '@theme/CodeBlock'

import styles from './index.module.css'

const typescriptCode = `import { 
  Workflow, 
  NormalJob, 
  Step, 
  expressions as ex
} from '@github-actions-workflow-ts/lib'
import { 
  ActionsCheckoutV4, 
  ActionsSetupNodeV4 
} from '@github-actions-workflow-ts/actions'

// Typed actions: autocomplete on inputs, typed outputs
const checkout = new ActionsCheckoutV4({ name: 'Checkout' })

const setupNode = new ActionsSetupNodeV4({
  id: 'setup-node',
  name: 'Setup Node.js',
  with: { 'node-version': '20.x', cache: 'npm' },
})

// Plain steps work too
const test = new Step({
  name: 'Run tests',
  run: 'npm test',
  env: { CI: 'true', NODE_AUTH_TOKEN: ex.secret('NPM_TOKEN') },
})

const testJob = new NormalJob('test', {
  'runs-on': 'ubuntu-latest',
}).addSteps([checkout, setupNode, test])

export const ci = new Workflow('ci', {
  name: 'CI',
  on: {
    push: { branches: ['main'] },
    pull_request: { branches: ['main'] },
  },
}).addJobs([testJob])`

const yamlOutput = `# Generated by github-actions-workflow-ts
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Run tests
        run: npm test
        env:
          CI: "true"
          NODE_AUTH_TOKEN: \${{ secrets.NPM_TOKEN }}`

function HomepageHeader() {
  const { siteConfig } = useDocusaurusContext()
  return (
    <header className={clsx('hero hero--primary', styles.heroBanner)}>
      <div className="container">
        <img
          src="/img/logo.png"
          alt="github-actions-workflow-ts logo"
          className={styles.heroLogo}
        />
        <Heading as="h1" className="hero__title">
          {siteConfig.title}
        </Heading>
        <p className="hero__subtitle">{siteConfig.tagline}</p>
        <div className={styles.buttons}>
          <Link
            className="button button--secondary button--lg"
            to="/docs/getting-started/installation"
          >
            Get Started
          </Link>
          <Link
            className="button button--outline button--secondary button--lg"
            to="/docs/getting-started/quick-start"
            style={{ marginLeft: '1rem' }}
          >
            Quick Start
          </Link>
        </div>
      </div>
    </header>
  )
}

function Feature({
  title,
  description,
}: {
  title: string
  description: string
}) {
  return (
    <div className={clsx('col col--4')}>
      <div className="text--center padding-horiz--md">
        <Heading as="h3">{title}</Heading>
        <p>{description}</p>
      </div>
    </div>
  )
}

function HomepageFeatures() {
  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row">
          <Feature
            title="Type Safety"
            description="Full TypeScript support with auto-generated types from the official GitHub Actions schema. Catch errors at compile time."
          />
          <Feature
            title="Reusable Components"
            description="Define steps, jobs, and workflows once and reuse them across your projects. No more copy-pasting YAML."
          />
          <Feature
            title="Zero Dependencies"
            description="The core library has zero runtime dependencies and works in both ESM and CommonJS projects."
          />
        </div>
      </div>
    </section>
  )
}

function CodeComparison() {
  return (
    <section className="container margin-vert--xl">
      <Heading as="h2" className="text--center margin-bottom--lg">
        Write TypeScript, Generate YAML
      </Heading>

      {/* Step 1: TypeScript */}
      <div className={styles.step}>
        <div className={styles.stepNumber}>1</div>
        <div className={styles.stepContent}>
          <p className={styles.stepLabel}>Write your workflow in TypeScript</p>
          <CodeBlock language="typescript" title="workflows/ci.wac.ts">
            {typescriptCode}
          </CodeBlock>
        </div>
      </div>

      {/* Step 2: Run command */}
      <div className={styles.step}>
        <div className={styles.stepNumber}>2</div>
        <div className={styles.stepContent}>
          <p className={styles.stepLabel}>Run the build command</p>
          <CodeBlock language="bash">npx gwf build</CodeBlock>
        </div>
      </div>

      {/* Step 3: YAML output */}
      <div className={styles.step}>
        <div className={styles.stepNumber}>3</div>
        <div className={styles.stepContent}>
          <p className={styles.stepLabel}>
            Get your generated YAML workflow file
          </p>
          <CodeBlock language="yaml" title=".github/workflows/ci.yml">
            {yamlOutput}
          </CodeBlock>
        </div>
      </div>

      <div className="text--center margin-top--xl">
        <Link
          className={clsx(
            'button button--primary button--lg',
            styles.ctaButton,
          )}
          to="/docs/getting-started/quick-start"
        >
          Get Started
        </Link>
      </div>
    </section>
  )
}

export default function Home(): ReactNode {
  return (
    <Layout
      title="Home"
      description="Write GitHub Actions workflows in TypeScript instead of YAML"
    >
      <HomepageHeader />
      <main>
        <HomepageFeatures />
        <CodeComparison />
      </main>
    </Layout>
  )
}
